### ISSUE TITLE
Core does not find existing save when running same exact rom in a different folder

### ISSUE THREAD

**Issue by naveedster** [agg23/openfpga-SNES#17]
This is a quality of life issue, but many people will probably experience this.  I have my roms organized alphabetically, but also by genre. So, when I was browsing, I first ran the Zelda rom from my Genre folder, saved the game. Next time I opened the exact same rom from the alphabetical folder, and it did not find my previous save. Had to keep selecting the rom from the same subfolder, otherwise it counted as a different save.

**Comment by juraisa** [comment]
This should be the expected behavior in my opinion. An individual ROM entity should have an individual save associated with it, not the expectation that you can run the ROM from any random path and always have the same save load

**Comment by agg23** [comment]
I also agree this is expected behavior, but I guess it's an ok feature request for Analogue.

**Comment by HeyItsLollie** [comment]
This issue is Pocket's doing, and not specific to any core. Analogue Pocket stores save files in a different folder, aptly named "Saves". The "Saves" folder mirrors the structure of your "Assets" folder and subfolders.

Basically, if you move your game file to a new folder, you also have to move your .sav file to an identically-named folder.

![explorer - 2022-09-18 - 13-58-51](https://user-images.githubusercontent.com/30498581/190885109-d41e5330-d221-4705-84f2-2b5ddca8f1ee.png)
