### ISSUE TITLE
Rendering Ranger (Japan) not working

### ISSUE THREAD

**Issue by KelSolar** [agg23/openfpga-SNES#53]
This is to my knowledge the only game not working on the SNES core. Only the Virgin logo loads up but then nothing more.

**Comment by agg23** [comment]
This is a known issue with the upstream MiSTer core (https://github.com/MiSTer-devel/SNES_MiSTer/issues/292). It seems that the game was poorly programmed and even has issues on real hardware. There's a hacky patch provided that may resolve the issue

I'm going to close this since it is known upstream
