### ISSUE TITLE
Control Mapping on a per-game basis rather than a global core setting

### ISSUE THREAD

**Issue by daBEARS40** [agg23/openfpga-SNES#87]
I find myself constantly re-working the controls based on what feels better between handheld & docked. Having one control scheme per game exacerbates the issue for me. In an ideal world there would be per-game handheld/docked individual mapping, but that would be outside the scope of this feature request. Per game control mapping would be an excellent addition if at all possible.

Thanks!

**Comment by agg23** [comment]
Unfortunately that's not really something that cores themselves can reasonably do. The existing UI is entirely up to Analogue, and replicating that would be expensive and not even possible on some cores (NES) due to space constraints.

However, I have forwarded this request to Analogue, so at least now they should be tracking it, even if we don't know if it will be acted on.
