### ISSUE TITLE
crackling and popping audio

### ISSUE THREAD

**Issue by naveedster** [agg23/openfpga-SNES#9]
It’s very faint, but, crackling and popping audio is audible and especially noticeable when listening on headphones. Noticed on star Fox 2 intro menu, and on Super Metroid.

**Comment by robhlark** [comment]
I have also noticed seemingly randomly occuring faint crackling/popping audio when listening with headphones. I've tested Super Mario All-Stars + Super Mario World (USA), The Legend of Zelda - A Link to the Past (USA) and Super Metroid (Japan, USA) and all have the same audio popping issue. I have also tested other cores (by spiritualized1997) and have not found the audio popping issue there.

Great work on this SNES core so far otherwise, thanks!

**Comment by thedrdodo** [comment]
Can confirm this. It's especially noticeable with headphones on. Super Mario World and Sim City both exhibit it. Most prevalent with Sim City imo.

**Comment by BooBerry** [comment]
Can confirm this too. But call me crazy if you want, but it kinda sounds like the audio is clipping when the pops happen. Like it's too loud for the speakers to handle or something.

**Comment by NotSure47247323** [comment]
Getting the same issue via dock on Chrono Trigger US.

**Comment by naveedster** [comment]
I believe that it’s happening in pretty much every title to some extent you can just hear it more in certain games
